version: "3"
services:
  weather-monitor:
    build: .
    volumes:
      - ./:/opt/weather-monitor
      - ./data/weather-monitor:/data/weather-monitor
      - ./logs/weather-monitor:/logs/weather-monitor
    links:
      - notifyd
  notifyd:
    image: noyuno/notifyd
    #build: notifyd
    restart: always
    ports:
      - "5050:5050"
    volumes:
      #- ./notifyd:/opt/notifyd
      - ./data/notifyd:/data/notifyd
      - ./logs/notifyd:/logs/notifyd
    environment:
      DEPLOY: /data/notifyd
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      NOTIFYD_TOKEN: "${NOTIFYD_TOKEN}"
      DISCORD_CHANNEL_NAME: p4
      PORT: 5050
